global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using TicketWise.Application.Contracts.Persistence;
global using TicketWise.Core.Common;
global using TicketWise.Core.Entities;
global using TicketWise.Persistence.Repositories;
